### ISSUE TITLE
Bug: '+ button' on search results page won't produce note on iPhone (Safari + Chrome)

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#211]
On **iPhone** '+' button won't allow a publication note to be made from search results page on safari or chrome. 

- Works fine on **Android**, a note icon does open note.
- Works fine on **desktop** on safari and chrome

**Comment by ajburls** [comment]
That was supposed to be titled
"Bug on iPhone search results page"

**Comment by SimonLab** [comment]
@ajburls this issue might be caused by an old cached version on your iphone. Could you logout and login again to check if the issue is still here, thanks

**Comment by ajburls** [comment]
@SimonLab I logged out and logged in again but problem still there. Remind me how to clear cache on an iphone and I will try that.

**Comment by ajburls** [comment]
@SimonLab also switched off phone and switched back on - not cured.

**Comment by ajburls** [comment]
@SimonLab I also tried clearing all website data and history from Safari - not cured

**Comment by markwilliamfirth** [comment]
@SimonLab @Cleop I don't have an iPhone - does one of you have one? Is the issue reproducible?

**Comment by SimonLab** [comment]
I suspect ```window.location.replace``` to not work properly on ios with safari even if it looks ok: (https://developer.mozilla.org/en-US/docs/Web/API/Location/replace)
![image](https://user-images.githubusercontent.com/6057298/30182515-fb637252-940e-11e7-8490-32dd86dcb5ad.png)

I'll try this and see if I can test it tomorrow on an iphone

**Comment by SimonLab** [comment]
@ajburls could you try again this issue, I've also reset the database to make sure we have the last version of the application, thanks

**Comment by ajburls** [comment]
Still not working. I deleted cache etc etc first.

**Comment by SimonLab** [comment]
Thanks for testing @ajburls I manage to find an iphone which make it easier to debug.
The event listner on the "+" button is not trigger this might be caused by a conflict with the other event listner used when users clicked on the evidence links. I will refactor the code now to only use one event listener:
https://github.com/dwyl/best-evidence/blob/3b0ab704a93064e476098219bc7ed9210f97b4c4/web/static/js/evidence_socket.js#L20-L54

**Comment by SimonLab** [comment]
@ajburls could you please test this issue on staging. I think this should be resolved now, thanks.

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue if you are happy?

**Comment by ajburls** [comment]
@markwilliamfirth This problem still exists on  the iPhone and prevents notes being added from a search. However, I wonder whether there may be a cookie problem as when I log in with the same ID and password as on the Android I get different results (however the results I get are the same results as on the tablet). Please advise. If I need to uninstall and remove cache should this be on android or iphone

**Comment by ajburls** [comment]
@markwilliamfirth @SimonLab this bug now occurring on Android since I have re-set everything (it wasn't beforehand).

**Comment by markwilliamfirth** [comment]
@ajburls we've just tested again on our side and we think there might still be an issue here

Simon is going to reset the database and to make sure the application is the latest version an then we'll tag you when we think it's working again

**Comment by SimonLab** [comment]
I manage to target the issue on ios. This is due to the fact that by default ios use "touch" event instead of "click" event. An easy solution is to add the style ```cursor: pointer``` to our clickable elements.
https://stackoverflow.com/questions/3705937/document-click-not-working-correctly-on-iphone-jquery

**Comment by SimonLab** [comment]
@ajburls I think this is fixed now, could you test on your side again? Thanks

**Comment by ajburls** [comment]
@SimonLab Not totally fixed. It worked for first publication I clicked + for on iPhone and then not for subsequent ones. It would open previously written notes, however.  I went and tried another search and initially it worked then stopped.

**Comment by SimonLab** [comment]
Sorry I was a bit quick to assign the "please-test" label. I spotted the error too, it should be fix soon (https://github.com/dwyl/best-evidence/pull/228). Thanks again for testing that

**Comment by ajburls** [comment]
@SimonLab No worries - I am just eager to get the final version onto BestEvidence.Info as I am preparing some notes for the students to whom we are giving the app tomorrow morning and I wanted to record some videos and prepare a leaflet to get them started :-)

**Comment by SimonLab** [comment]
@ajburls could you please test again? Depending on your internet connection it's possible that the "add note" page take a couple of seconds to load after clicking on the add icon but otherwise it should be ok now.

**Comment by ajburls** [comment]
@SimonLab This appears to be working well now on iPHone. Will test on other devices. Unfortunately though it seems to have introduced (or perhaps the first time it has occurred?) a bug. If I search on "Arnica Bruise" it gives me an internal server error. This is a search I have done before with no problem. It is letting me do other searches OK.

**Comment by SimonLab** [comment]
@ajburls I'm going to reset the database if it's ok, I changed the structure so it's possible you had a conflict with your search with the old data. 
Is it ok to delete the current data on staging now?

**Comment by ajburls** [comment]
@SimonLab OK just tested on notebook computer and getting same error

**Comment by SimonLab** [comment]
@ajburls not sure if you saw my previous comment: https://github.com/dwyl/best-evidence/issues/211#issuecomment-331185218
I just wanted to check with you if it's ok if I reset the database now, it should fix the errors

**Comment by ajburls** [comment]
@SimonLab PLease do but this may not solve problem as it has just happened with a different search term, which was working when I was testing failure of "arnica bruise" search. I also notice that the search list at the bottom of the search page is not consistently adding the latest search term. I thought this might be because a search was done before but I tested this an error is inconsistent (although reproducible).

**Comment by SimonLab** [comment]
@ajburls I've just reset the database. To be sure that you don't have an old version running could you uninstall and install again the application on your phones? It should automatically be updated on desktop. 
You will have to crate an account again. Let me know if you still have the previous error I couldn't reproduce it at this stage but had it a couple of days before when I changed the structure of the database and resetting it fixed it.
Thanks

**Comment by ajburls** [comment]
@SimonLab @markwilliamfirth I removed cookies from computer and tested it multiple searches and a few repeat searches on the computer and all was well. Then I deleted from iPhone tried on iPhone and all was well. Then the problem occurred again (strangely with "arnica bruise" again which had worked since re-set). Now problem occurs on computer too. I wondered whether I didn't remove all the history and cache properly from the iPhone. (Can you tell me how to do that for an iPhone please?) but it is strange that it worked for arnica bruise once again and then not.

**Comment by ajburls** [comment]
@SimonLab @markwilliamfirth You will need to re-set again, even if this was my fault and caused by an old cache, before I try after following whatever instructions you now send. (Because it is web-based it doesn't appear in list of apps like other apps do.)

**Comment by SimonLab** [comment]
@ajburls I will reset now. It's difficult to debug as I couldn't manage to reproduce the error. Make sure that you are logged out and uninstall the application on all devices before retrying. If the error happen again coulld you send some screenshot and the steps which produced the error. Thanks

**Comment by SimonLab** [comment]
@ajburls the database is now reset. I'll do more test on my side to try to reproduce your error. Let me know if it is still an issue. It might be also good to test on production maybe it's due to a limitation of service on the stating from Heroku.
Are you happy for me to reset the database and deploy on production?

**Comment by ajburls** [comment]
OK - I deleted everything from both phones and from computer. I started testing on computer and it caused the problem after about ten or eleven searches. It occurred after I (successfully) searched for a term that I had previously searched for and which was no longer appearing in the list below the search box. When I went back to search from the results, I clicked on the top search showing and got internal server error 
![capture](https://user-images.githubusercontent.com/30235568/30706631-dab12ab2-9ef0-11e7-8c95-8eca333530e8.PNG)

Pretty sure it was this same type of sequence that produced error before - i.e.  following a search for an historical search that then did not show up in the search list below search box and then clicking on top search to search again.

This is first time though that it happened directly from laptop. Previously first occurrence was always on iPhone and only afterwards did problem occur on laptop.

If you want to re-set I can use Camtasia to record a sequence and reproduce for you.

**Comment by ajburls** [comment]
@markwilliamfirth Please do re-set database and also deploy on production (although it would be good if you could re-set the production database tomorrow morning also, so that my testing searches are removed and we can have a clean dataset from the students we will be giving it to.)

**Comment by SimonLab** [comment]
@ajburls I manage to see why the error occurs. I've created a new issue for that https://github.com/dwyl/best-evidence/issues/229. I think this one can be tested again after if needed but I don't think the current bug should be related to this issue anymore

I will let you know when I have reset the database :+1:

**Comment by markwilliamfirth** [comment]
@ajburls Hello! please can you test and close this issue if this is no longer an issue on the staging app?

**Comment by ajburls** [comment]
THis is working OK now
