### ISSUE TITLE
Bug: publications duplicating

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#221]
Not sure if this is an app issue or a trip big with two unique identifiers for same resource.
![screenshot_20170907-230418](https://user-images.githubusercontent.com/30235568/30185401-84844086-9421-11e7-8f39-532523097030.png)

**Comment by SimonLab** [comment]
@ajburls do the notes linked to the publications are the same for the duplicates?

**Comment by ajburls** [comment]
@SimonLab yes

**Comment by SimonLab** [comment]
Thanks for confirming this. I think this might be caused when a user clicked multiple time on the same evidence link on a same search. I've added some constraint to avoid saving the same evidence link for a same search, so it should resolve this issue.

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue if you are happy?

**Comment by ajburls** [comment]
Problem still happening on Android - just tested now using "staging" link

**Comment by ajburls** [comment]
Further information on this bug - I am adding a note using android by clicking on a paper from a search. It then appears duplicated in notes (i.e. not that there are two notes but a single note appears twice. Picture from today 19th Sept.
![duplication bug](https://user-images.githubusercontent.com/30235568/30598592-0bc469a2-9d52-11e7-9f1d-955a906086b1.jpg)

**Comment by ajburls** [comment]
I can't test this error on the iPhone as the bug that prevents notes being added from a search is still there.

**Comment by ajburls** [comment]
@markwilliamfirth OK I re-set Android phone and now it is producing same results as iPhone and online and there are no duplicates
