### ISSUE TITLE
duplicate searches in database

### ISSUE THREAD

**Issue by SimonLab** [dwyl/best-evidence#229]
![image](https://user-images.githubusercontent.com/6057298/30707284-ee8bf66e-9ef2-11e7-88e2-08c2d8e47ba3.png)

The database manage to insert a duplicate search for the same user (search "burls", id 3). This should be allow as we have unique constraint on the database. 
This looks like a race race condition (multipe items are inserted at the same time) however we can see that there is 2mn laps between the two inserts :thinking: 

I will verify the constraints on the database, and if necessary add a more manually check to see if a search term already exists in the database.

@ajburls is your internet connection slow, I try to figure out why the duplicates are inserted in the database and it can happen when the application attempt to send the same search multiple times? Or when you click on the search button, do you double click?

**Comment by SimonLab** [comment]
@ajburls I've deploy the application on production, could you test it to see if you have the same error, thanks?

**Comment by ajburls** [comment]
@SimonLab I have just gone to https://www.bestevidence.info deleted all cookies and tried to set up a new account. I already had an account so I logged in and old history is there. Is that what was supposed to happen? I will continue to test, it's just that I thought the history would have been deleted.

**Comment by SimonLab** [comment]
@ajburls sorry I forgot to reset the database (I only deploy the last version of the application). I am working on a fix at the moment but as soon as a new version is ready I will deploy again and make sure I reset the database, thanks for the reminder :+1:

**Comment by ajburls** [comment]
@SimonLab I have done a few searches and the sequences that I was doing before and all is well. The only thing is that the recent searches doesn't update with the most recent searches if they were ever done in the past. I have both phone switched off and will now try them.

**Comment by ajburls** [comment]
@SimonLab It was going really well but then I got the internal server error. Was using iPhone. Android still switched off. Now error occurring on computer on "ranitidine" :-(

**Comment by SimonLab** [comment]
@ajburls I've added some check on the code and deployed on staging and production and reset the database. Could you try again to reproduce the error. Thanks again for testing this, I'll try to keep an eye on the server logs to see if I can catch more information about the error if it occurs

**Comment by ajburls** [comment]
@SimonLab @markwilliamfirth Tested so far on computer and looking good :-)
All searches worked with various repeats etc. but also most recent search is showing in "recent searches", even is done before so that bug appears to be fixed.

Now to test with the killer iPhone.... ;-)

**Comment by SimonLab** [comment]
Thanks @ajburls I saw a lot of green tea searches :)
I'll keep an eye on the logs

**Comment by ajburls** [comment]
@SimonLab I am afraid the apple was poisoned. I have just had the internal server error.

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/30711583-1bcebef0-9f01-11e7-93cb-2dbc3db87c22.png)

I think there was an error :(

**Comment by SimonLab** [comment]
@ajburls I finally manage to reproduce the error on my side! I think it is due to a trailing space on the searches which is not removed when we look in the database if the search term already exists.
I will create a fix soon for this and we can test again. Sorry it takes a bit of time to find out what was happening. I have now a better idea on what is the issue and confident we can fix it soon.

**Comment by ajburls** [comment]
@SimonLab Well done!  I have created a second account which I have been using on the Android and haven't managed to break it yet but I might try doing so deliberately now I know the problem ;-)

**Comment by ajburls** [comment]
@SimonLab Yup - did it on Android. You are right about source of problem. I am about to leave office and will be going home so not able to test for a while. Could you re-set database when you next load up so that it is as clean as possible for when we start using it.

**Comment by ajburls** [comment]
@SimonLab P.S. I really appreciate the efforts you and Mark have made to get this sorted for tomorrow. I am very grateful.

**Comment by SimonLab** [comment]
Thanks for confirming.
Yes I will reset staging and production. Hopefully this is the only source of the bug and everything will be fix. Let us know if you still see the issue after the fix is merged.
I will let you know when everything is ready to be tested.
Thanks

**Comment by SimonLab** [comment]
@ajburls I have now deployed on staging and production and I reset the database. Let us know if everything works ok :+1:

**Comment by ajburls** [comment]
Thanks. I'll let you know how it goes.  :-)

Sent from my iPhone

On 21 Sep 2017, at 21:33, Simon <notifications@github.com<mailto:notifications@github.com>> wrote:


@ajburls<https://github.com/ajburls> I have now deployed on staging and production and I reset the database. Let us know if everything works ok 👍

**Comment by ajburls** [comment]
@simonlab Unfortunately still getting internal error searching. Happened on iPhone editing a long search

**Comment by SimonLab** [comment]
Thanks for testing, I think this is a new bug:
![image](https://user-images.githubusercontent.com/6057298/30731760-39253a90-9f67-11e7-974e-0ff705660b40.png)

This is due to a limit on the search term in the database.

**Comment by markwilliamfirth** [comment]
@ajburls Hello! please can you test and close this issue if this is no longer an issue on the staging app?
